### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by NoNamePro0** [LucaHerzog/SoulGames-StickIT#1]
Hello, in a Git repository no .jar files and artifacts belong in, or other binarys.
Only the code, the JAR file, can be attached as a file when released.

You can use the `.gitignore` file that does not automatically commit the files that are in the` .gitignore`.

You can find `.gitignore` templates for various programming languages at [github / gitignore](https://github.com/github/gitignore).

**Comment by lucaherzog** [comment]
This is a outdated plugin. I created at 10 months ago.
